name = "webapp"
compatibility_date = "2025-01-01"

# Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

# Environment variables for local development
# Production variables should be set in Cloudflare dashboard
[vars]
# Add non-secret environment variables here if needed
